version: '3.7'

services:
  postgres:
    build: ./postgres
    restart: always
    volumes:
      - ./db:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'

  web:
    restart: always
    build: ./rates
    environment:
      ENV: "Development"
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
      OAUTHLIB_INSECURE_TRANSPORT: 1
      OAUTHLIB_RELAX_TOKEN_SCOPE: 1
    ports:
      - "3000:3000"
    expose:
      - 3000
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
      - .:/opt/services/src/app/
    env_file: .env
    command: gunicorn -b :3000 wsgi
